controllers/AppController.php
<?php

namespace app\controllers;

use app\components\AppHelper;
use app\components\AppWebUser;
use app\components\ArrayHelper;
use app\components\DummyUser;
use Exception;
use uhi67\eduidsp\Saml;
use Yii;
use yii\base\Action;
use yii\base\InvalidConfigException;
use yii\web\Controller;
use yii\web\YiiAsset;

/**
 * Class AppController
 *
 * - Retrieves current user display data into $this->user
 * - Creates application's main menu
 *
 * @property-read Saml $saml
 */
class AppController extends Controller {
	public $mainMenu = [];
	public $userPanel;	// render data for login panel
	/** @var int $itemid value of id parameter */
	public $itemid;

	/** @var DummyUser $appUser -- the logged in appUser or null */
	public $appUser;
	/** @var AppWebUser $user -- the User component of Yii */
	public $user;

	/**
	 * @param Action $action
	 *
	 * @return bool
	 * @throws
	 */
	public function beforeAction($action) {
		if (!parent::beforeAction($action)) {
			return false;
		}

		$this->user = Yii::$app->user;
		$this->appUser = $this->user->identity;
		$this->itemid = Yii::$app->request->get('id');

    	// Login sáv adatainak előállítása
		$this->userPanel = [
			'isauthenticated' => !!$this->appUser,
			'displayname' => $this->appUser ? $this->appUser->displayname : 'Not logged in',
			'enabled' => $this->appUser ? $this->appUser->enabled : false,
			'id' => $this->appUser ? $this->appUser->id : null,
		];

		// Naplózás
		if(!in_array($this->action->uniqueId, [])) $this->logAccess();

		return true; // or false to not run the action
	}

	/**
	 * @param string $view
	 * @param array $params
	 *
	 * @return string
	 * @throws InvalidConfigException
	 */
	public function render($view, $params = []) {
		$saml = $this->saml;
		$mainMenu = [
		];

		if($saml && $saml->isAuthenticated()) {
			$loginMenu = [
				[
					'enabled' => true,
					'caption' => $saml->get('displayName', 0),
					'title' => 'Személyes menü',
					'class' => '',
					'action' => '/user/own',
					'icon' => 'fa-user',
					'items'=> [
						[
							'enabled' => true,
							'caption' => 'Saját adataim',
							'class' => '',
							'action' => '/user/own',
							'icon' => 'fa-user',
						],
						[
							'enabled' => true,
							'caption' => 'Kilépés',
							'action' => '/logout',
							'icon' => 'fa-sign-out-alt',
						]
					]
				],
			];
			$mainMenu = array_merge($mainMenu, [
				[
					'enabled' => 1,
					'caption' => 'Dokumentáció',
					'icon' => 'fa-book',
					'title' => 'Felhasználói útmutató',
					'action' => ['doc/index'],
				]
			]);
		}
		else {
			$loginMenu[] =
				[
					'enabled' => true,
					'caption' => Yii::t('yii', 'Login'),
					'action' => '/login',
				];
		}

		$this->mainMenu = array_merge($mainMenu, $this->mainMenu, [
			/*
			// Nyilvános menüpontok, ha vannak
				[
					'enabled' => 1,
					'caption' => 'Dokumentáció',
					'icon' => 'fa-book',
					'title' => 'Felhasználói útmutató',
					'action' => $saml->isAuthenticated() ? '/doc' : '/doc/view',
				]
			*/
			], $loginMenu);

		$params['appUser'] = $this->appUser;
		$params['user'] = $this->user;

		if(file_exists(Yii::getAlias('@webroot/js/'.$this->id.'.js')))
			$this->getView()->registerJsFile('@web/js/'.$this->id.'.js?ver='.AppHelper::version(), ['depends'=>[YiiAsset::class]]);

		return Parent::render($view, $params);
	}

	/**
	 * Returns authentication source
	 *
	 * @return Saml
	 */
	public function getSaml() {
		/** @noinspection PhpUndefinedFieldInspection */
		return Yii::$app->has('saml') ? Yii::$app->saml : null;
	}

	/**
	 * @param string|array|null $message
	 * @param array|null $params
	 * @param string $category
	 *
	 * @throws Exception
	 */
	public function logAccess($message=null, $params=null, $category='app-access') {
		$action = $this->action;
		$param = Yii::$app->request->queryParams;
		if(is_array($params)) $param = array_merge($param, $params);
		Yii::info(array_filter([
			'page' => $action->controller->uniqueId,
			'act' => $action->id,
			'target' => is_numeric($this->itemid) ? $this->itemid : ArrayHelper::getValue($param, 'id'),
			'message' => $message,
			'param' => $param
		], function($v) { return $v !== null; }), $category);
	}

	/**
	 * @param string|array|null $message
	 * @param array|null $params
	 *
	 * @throws Exception
	 */
	public function logAction($message, $params=null) {
		$this->logAccess($message, $params, 'app-action');
	}
}

controllers/SiteController.php
<?php /** @noinspection PhpUnused */

namespace app\controllers;

use app\components\AppHelper;
use app\components\ArrayHelper;
use app\components\DummyUser;
use uhi67\eduidsp\Saml;
use uhi67\envhelper\EnvHelper;
use Yii;
use yii\base\InvalidConfigException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class SiteController extends AppController {

	/**
	 * Displays homepage.
	 *
	 * @return string
	 * @throws InvalidConfigException
	 */
    public function actionIndex() {
        return $this->render('index');
    }

	/**
	 * Logout action.
	 *
	 * @return Response
	 * @throws
	 */
    public function actionLogout() {
		Yii::$app->user->logout(true);
		if(Yii::$app->saml->isAuthenticated()) Yii::$app->saml->logout();
		return $this->goHome();
    }

	/**
	 * Login action.
	 *
	 * @return Response|string
	 * @throws \Exception
	 * @noinspection PhpFullyQualifiedNameUsageInspection
	 */
	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$saml = $this->saml;
		if(!$saml) {
			AppHelper::sendMessage('Nincs konfigurálva a belépési szolgáltatás!', 'danger');
			return $this->redirect('/');
		}

		$idp = EnvHelper::getEnv('idp', null);
		$disco = EnvHelper::getEnv('disco', null);
        $baseUrl = EnvHelper::getEnv('APP_BASEURL', null);
		$params = [
            'ReturnTo' => $baseUrl,
        ];
		if($idp && $disco) $params['saml:idp'] = $idp;
		if(!$saml->isAuthenticated()) $saml->requireAuth($params);

		$attributes = $saml->getAttributes();
		$id = ArrayHelper::getValue($attributes, $saml->idAttribute);
		if(is_array($id)) $id = $id[0];
		$user = new DummyUser([
			'id' => $id,
			'attributes' => $attributes
		]);
		Yii::$app->user->login($user, 8*60*60);
		return $this->redirect('/');
	}

	/**
	 * @param string|null $id -- dokumentációs oldal szöveges azonosítója
	 *
	 * @return string
	 * @throws NotFoundHttpException
	 */
	public function actionDoc($id=null) {
		if(!$id) $id = 'index';
		$docfile = dirname(__dir__)."/doc/$id.md";
		if(!file_exists($docfile)) throw new NotFoundHttpException("Az `$id` oldal nem található");

		return $this->render('doc', [
			'doc' => file_get_contents($docfile),
		]);
	}

	public function actionOwn() {
		/** @var Saml $saml */
		return $this->render('own', [
			'user' => $this->appUser,
			'isAuth' => $this->saml->isAuthenticated(),
			'attributes' => $this->saml->attributes,
		]);
	}
}

views/layouts/main.php
<?php /** @noinspection PhpUnhandledExceptionInspection */

/** @var $this View */
/** @var $content string */

use app\assets\FishAsset;
use app\components\AppHelper;
use app\widgets\Alert;
use uhi67\eduidsp\SamlAsset;
use uhi67\umenu\UMenu;
use uhi67\umenu\UMenuAsset;
use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\web\View;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
UMenuAsset::register($this);
SamlAsset::register($this);
$fishAsset = FishAsset::register($this);

$brandName = mb_strtoupper('My Company');
$appName = mb_strtoupper(Yii::$app->name);

$footerBrand = AppHelper::getParam('footerBrand', 'PTE');
$version = AppHelper::version();
$versionx = $version ? 'Verzió: ' . Html::a($version, ['site/doc', 'id'=>'version']) : '';
$mainMenu = $this->context->mainMenu;
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Author" content="Uherkovich Peter">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap layout-main">
    <?php
		/** @noinspection PhpUnhandledExceptionInspection */
		$color = AppHelper::getParam('color', null);
		$options = ['class' => 'navbar-fixed-top app-top navbar-dark navbar-expand-md'];
		if($color) $options['style'] = ['background-color'=>$color];
		NavBar::begin([
			'brandLabel' => Html::tag('div',
			    Html::img($fishAsset->baseUrl . '/icons/ssplogo-fish-small.png') .
			    Html::tag('div',
					Html::tag('div', $brandName, ['class'=>'brand-header']).
			        Html::tag('div', $appName, ['class'=>'brand-slogan']),
			        ['class'=>'brand-name']),
			    ['class'=>'brand-group']),
			'brandUrl' => Yii::$app->homeUrl,
			'options' => $options,
		]);
    ?>
	<?=
		/** @noinspection PhpUnhandledExceptionInspection */
		Nav::widget([
			'options' => ['class' => 'navbar-nav navbar-right ml-md-auto'],
			'items' => (new UMenu(['items'=>$mainMenu]))->navItems(),
			'encodeLabels' => false,
		])
	?>
	<?php NavBar::end(); ?>

    <div class="container">
        <?= /** @noinspection PhpUnhandledExceptionInspection */
			Breadcrumbs::widget([
            	'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= /** @noinspection PhpUnhandledExceptionInspection */
        	Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
		<p class="pull-left"><?= $versionx ?></p>
        <p class="pull-right">&copy; <?= $footerBrand ?> <?= date('Y') ?></p>
    </div>
</footer>

<div id="error-dialog" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Modal title</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/doc.php
<?php

use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $doc string */

$this->title = 'Organizational Voting System';
uhi67\showdown\ShowdownAsset::register($this);
$this->registerJsFile(Url::to(['/js/doc.js']), ['depends'=>'uhi67\showdown\ShowdownAsset']);
?>
<div class="site-index">
    <div class="body-content">
		<div class="alert alert-info">Kivonat a dokumentációból</div>
		<div class="showdown">
			<pre class="markdown"><?= $doc ?></pre>
		</div>
    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = '';
?>
<div class="site-index">
    <div class="body-content">
		<h2>Látogatóinknak</h2>
		<p>Ez egy Yii2 mintaalkalmazás a SAML login bemutatásához. A belépést a composerrel beépített SimpleSAMLphp modul biztosítja.</p>
    </div>
</div>

views/site/own.php
<?php /** @noinspection PhpUnhandledExceptionInspection */

use app\components\AppWebUser;
use app\components\ArrayHelper;
use uhi67\eduidsp\Saml;
use yii\helpers\Html;
use yii\web\View;
use yii\web\YiiAsset;
use yii\widgets\DetailView;

/* @var $this View */
/* @var $isAuth bool */
/* @var $attributes array */
/* @var $user AppWebUser */

$this->title = ArrayHelper::getValue($attributes, 'displayName', ArrayHelper::getValue($attributes, 'uid'));
if(is_array($this->title)) $this->title = $this->title[0];
$this->params['breadcrumbs'][] = 'Saját adatok';
YiiAsset::register($this);
?>
<div class="app-user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if(!$user->isGuest) : ?>
		<h2>Alkalmazásban tárolt adatok</h2>
		<p>Ez az alkalmazás nem tárol felhasználói adatokat.</p>
	<?php endif; ?>

	<?php if($isAuth) : ?>
		<h2>Azonosító szervezettől kapott adatok</h2>

		<?= /** @noinspection PhpUnhandledExceptionInspection */
		DetailView::widget([
			'options' => ['class'=>'table detail-view attributes'],
			'model' => array_map(function($a) {
				if(is_array($a) && count($a)>0 && is_array($a[0])) {
					$a = array_map(function($b) { return implode(', ', $b);}, $a);
				}
				if(is_array($a) && count($a) >1) return Html::ul($a);
				if(is_array($a) && count($a)==1) return $a[0];
				if(is_array($a) && count($a)==0) return 'nincs megadva';
				return $a;
			}, $attributes),
			'attributes' => array_map(function($key, $values) { return [
				'label' => Saml::translateAttributeName($key, Yii::$app->language),
				'format' => 'raw',
				'value' => Saml::formatAttribute($key, $values),
			];}, array_keys($attributes), array_values($attributes)),
		]) ?>
	<?php else : ?>
		<div class="alert alert-warning">Ön nincs belépve.</div>
	<?php endif; ?>

</div>